name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test